version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    labels: ["dependencies"]
    ignore:
      - dependency-name: "AutoMapper"
        update-types: ["version-update:semver-major"]
      - dependency-name: "EPPlus"
        update-types: ["version-update:semver-major"]
    groups:
      microsoft-bcl:
        patterns:
          - "Microsoft.*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    labels: ["actions-updates"]
