kind: Service
apiVersion: v1
metadata:
  name: facturacion-service-util
  annotations:    
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: facturacion
    tier: service-util
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
    name: http