name: "Azure Deploy Template"

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      slot:
        default: 'production'
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

permissions:
  inherit: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🧰 Descargar artefacto del build
        uses: actions/download-artifact@v5
        with:
          name: backend-artifact
          path: ./publish

      - name: ✅ Validar artefacto
        run: |
          if [ ! -d "./publish" ]; then
            echo "❌ No se encontró el artefacto."
            exit 1
          fi

      - name: 🔐 Login Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-oidc: true

      - name: 🚀 Deploy a Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ inputs.app_name }}
          slot-name: ${{ inputs.slot }}
          package: ./publish
          runtime-stack: 'DOTNETCORE|8.0'
          startup-command: 'dotnet Scharff.API.Utils.dll'
